name: JMH Benchmark
on:
  push:
    branches:
      - master

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build with Maven'
        run: mvn clean install
      - name: 'Upload Java Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'jmh.jar'
          path: 'jmh/target/jmh-1.0-SNAPSHOT.jar'
  jmh-linux:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: 'jmh.jar'
          path: './'
      - name: 'Run JMH tests on linux'
        run: java -jar -Xms2G -Xmx2G -XX:+AlwaysPreTouch jmh.jar
